final_time = 7889238000  #250 years
#final_time = 12622780800  #400 years
#final_time = 31556952000 #1000 years
mesh_file = "bp1_sym.msh"

[seas]
type = "poisson"
lib = "bp1_sym.lua"
boundary = "boundary"
mu = "mu"
ref_normal = [1, 0]

[friction]
lib = "bp1_sym.lua"
a = "a"
eta = "eta"
sn_pre = "sn_pre"
tau_pre = "tau_pre"
Vinit = "Vinit"
    [friction.constant]
    b = 0.015
    V0 = 1.0e-6
    L = 0.008
    f0 = 0.6

[output]
prefix = "bp1_sym"
V_ref = 0.001
t_min = 0.05
t_max = 9460800

[solver]
bdf_custom_error_evaluation = false
bdf_custom_Newton_iteration = false
custom_time_step_adapter = false
adapt_wnormtype = "infinity"
ksp_type = "preonly"
pc_type = "lu"
pc_factor_mat_solver_type = "mumps"

    [solver.aseismic_slip]
    solution_size = "compact"
    problem_formulation="ode"
    type = "rk"
    rk_type = "5dp"
    bdf_order = 4
    S_atol = 1e-7
    S_rtol = 0
    psi_atol = 1.0e-7
    psi_rtol = 0
    V_atol = 0
    V_rtol = 1e-7

    [solver.earthquake]
    solution_size = "compact"
    problem_formulation="ode"
    type = "bdf"
    rk_type = "5dp"
    bdf_order = 4
    S_atol = 1e-7
    S_rtol = 0
    psi_atol = 1.0e-7
    psi_rtol = 0
    V_atol = 0
    V_rtol = 1e-7



