final_time = 7884000000
mesh_file = "bp1_sym.msh"

[seas]
type = "poisson"
lib = "bp1_sym.lua"
boundary = "boundary"
mu = "mu"
ref_normal = [1, 0]

[friction]
lib = "bp1_sym.lua"
a = "a"
eta = "eta"
sn_pre = "sn_pre"
tau_pre = "tau_pre"
Vinit = "Vinit"
    [friction.constant]
    b = 0.015
    V0 = 1.0e-6
    L = 0.008
    f0 = 0.6

[output]
prefix = "bp1_sym"
V_ref = 0.001
t_min = 0.05
t_max = 9460800

[solver]
ts_type = "bdf"
ts_rk_type = "5dp"
ts_bdf_order = 4
bdf_manual_error_evaluation = false
bdf_manual_Newton_iteration = false
ts_adapt_wnormtype = "infinity"
S_rtol = 0
S_atol = 1.0e-3
psi_rtol = 0
psi_atol_as = 1.0e-3
psi_atol_eq = 1.0e-7
ksp_type = "preonly"
pc_type = "lu"
pc_factor_mat_solver_type = "mumps"

